### PR TITLE
Incorporate queue/topic ID in ServiceBusFunction.

### LINKED ISSUE #416: Service Bus namespace not found on preview
Any example with a Service Bus namespace and Azure Function bound to its objects (e.g. [this one](https://github.com/pulumi/pulumi-azure/tree/master/examples/topic)) fails on the initial `pulumi preview`:

```
Invoke of 'azure:servicebus/getNamespace:getNamespace' failed: rpc error: code = Unknown 
desc = invocation of azure:servicebus/getNamespace:getNamespace returned an error: 
invoking azure:servicebus/getNamespace:getNamespace: ServiceBus Namespace 
"test119dc73a" was not found in Resource Group "test9d682d52" ()
at deserializeResponse (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\runtime\invoke.js:317:15)
at invokeSyncWorker (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\runtime\invoke.js:208:25)
at invokeSync (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\runtime\invoke.js:101:12)
at Object.invoke (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\runtime\invoke.js:84:24)
at Object.getNamespace (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\servicebus\getNamespace.ts:36:65)
at ServiceBusFunction.pulumi.all.apply (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\servicebus\zMixins.ts:328:37)
at C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\output.js:210:35         at Generator.next (<anonymous>)
at C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\output.js:21:71          at new Promise (<anonymous>)

    (node:27904) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
```

### PR DESCRIPTION
**Pull request by pgavlin**
We cannot call `getNamespace` until we are sure the namespace we want to
retrieve exists. Ensure that this is the case by incorporating the id of
the Queue or Topic that we're pulling the namespace and resource group name
off of into our `apply`.

Fixes #416.

### CODE REVIEW

**Comment by pgavlin** [comment]
Surprising that the tests for this failed--I can't repro the failure locally when I run manually. Looking into it now.

File: sdk/nodejs/servicebus/zMixins.ts [hunk 1]
```diff
@@ -305,8 +305,19 @@ export class ServiceBusFunction extends appservice.Function<ServiceBusContext, s
...
+        } else {
+            namespaceName = pulumi.all([args.topic!.namespaceName, args.topic!.id]).apply(([ns]) => ns);
+        }
+
+        let resourceGroupName;
+        if (args.queue && args.queue.resourceGroupName) {
+            resourceGroupName = pulumi.all([args.queue.resourceGroupName, args.queue.id]).apply(([rg]) => rg);
+        } else {
+            resourceGroupName = pulumi.all([args.topic!.resourceGroupName, args.topic!.id]).apply(([rg]) => rg);
+        }
```
Comment (mikhailshilkov) [inline sdk/nodejs/servicebus/zMixins.ts]: I think I'd rather keep the old definitions and add another `const id = ...` to point to the queue/topic id, then pass the `id` to the existing `pulumi.all` call down below. Feels like it could be a bit simpler.

Comment (pgavlin) [reply sdk/nodejs/servicebus/zMixins.ts]: Done.

File: sdk/nodejs/servicebus/zMixins.ts [hunk 2]
```diff
@@ -306,7 +306,9 @@ export class ServiceBusFunction extends appservice.Function<ServiceBusContext, s
         }
 
         const namespaceName = (args.queue && args.queue.namespaceName) || args.topic!.namespaceName;
+        const namespaceId = (args.queue && args.queue.namespaceName) ? args.queue.id : args.topic!.id;
         const resourceGroupName = (args.queue && args.queue.resourceGroupName) || args.topic!.resourceGroupName;
+        const resourceGroupId = (args.queue && args.queue.resourceGroupName) ? args.queue.id : args.topic!.id;
```
Comment (mikhailshilkov) [inline sdk/nodejs/servicebus/zMixins.ts]: 1. I think the names are a bit confusing: they are both a queue/topic ID, not namespace ID or resource group ID. 
2. Why do we need both?

File: sdk/nodejs/servicebus/zMixins.ts [hunk 3]
```diff
@@ -323,7 +325,7 @@ export class ServiceBusFunction extends appservice.Function<ServiceBusContext, s
             connection: bindingConnectionKey,
         } as ServiceBusBindingDefinition;
 
-        const namespace = pulumi.all([namespaceName, resourceGroupName])
+        const namespace = pulumi.all([namespaceName, resourceGroupName, namespaceId, resourceGroupId])
```
Comment (mikhailshilkov) [inline sdk/nodejs/servicebus/zMixins.ts]: It might be worth to add a short comment of why we add IDs and then ignore them in apply, so that we don't remove this later.

File: sdk/nodejs/eventhub/zMixins.ts [hunk 4]
```diff
@@ -214,7 +214,7 @@ export class EventHubFunction extends appservice.Function<EventHubContext, strin
             connection: bindingConnectionKey,
         } as EventHubBindingDefinition;
 
-        const namespace = pulumi.all([args.eventHub.namespaceName, args.eventHub.resourceGroupName])
+        const namespace = pulumi.all([args.eventHub.namespaceName, args.eventHub.resourceGroupName, args.eventHub.id])
```
Comment (mikhailshilkov) [inline sdk/nodejs/eventhub/zMixins.ts]: Good catch!

**Comment by mikhailshilkov** [comment]
It looks like the same tests still fail: https://travis-ci.com/pulumi/pulumi-azure/builds/137865790#L3021

File: sdk/nodejs/servicebus/zMixins.ts (hunk 2 above)
Comment (pgavlin) [reply sdk/nodejs/servicebus/zMixins.ts]: > I think the names are a bit confusing: they are both a queue/topic ID, not namespace ID or resource group ID.

Yes, but that's not how they're used.

> Why do we need both?

I would love it if we didn't, but it's not clear from the conditions whether or not it is safe to take _either_ the queue ID _or_ the topic ID (i.e. it's not clear whether those properties are mutually exclusive). If it is the case that the user must specify exactly one of those, then we don't need both.

**Comment by pgavlin** [comment]
> It looks like the same tests still fail: https://travis-ci.com/pulumi/pulumi-azure/builds/137865790#L3021

Yes. I looked into this and it turns out that this is because of the `UpgradeTest` feature of the integration testing framework. This feature first runs a test with the current version of the package under test, then links in the new version and runs it again. Because the current version has a bug that is causing these tests to fail, they cannot pass until the current version contains the bug fix in this PR.

File: sdk/nodejs/servicebus/zMixins.ts (hunk 3 above)
Comment (pgavlin) [reply sdk/nodejs/servicebus/zMixins.ts]: Will do.

File: sdk/nodejs/servicebus/zMixins.ts (hunk 2 above)
Comment (mikhailshilkov) [reply sdk/nodejs/servicebus/zMixins.ts]: Yes, the idea is that exactly one of the (queue, topic) has to be specified, which is enforced in the constructor [here](https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/servicebus/zMixins.ts#L292-L298)

Comment (pgavlin) [reply sdk/nodejs/servicebus/zMixins.ts]: Ah, perfect.

File: sdk/nodejs/servicebus/zMixins.ts [hunk 5]
```diff
@@ -305,6 +305,7 @@ export class ServiceBusFunction extends appservice.Function<ServiceBusContext, s
             throw new Error("[subscription] must be specified in combination with [topic]");
         }
 
+        const queueOrTopicId = (args.queue && args.queue.id) || args.topic!.id;
```
Comment (CyrusNajmabadi) [inline sdk/nodejs/servicebus/zMixins.ts]: if we move to TS 3.7+ we can start using `.?` and `??`.
