### PR TITLE
Re-enable EventGrid test

### LINKED ISSUE #1036: Eventgrid test broken
The acceptance test in `examples/eventgrid/` is (at the time of writing), broken in both the `master.yml` and `cron.yaml` flows:

* master: https://github.com/pulumi/pulumi-azure/runs/5250503578?check_suite_focus=true
* cron: https://github.com/pulumi/pulumi-azure/runs/5250566690?check_suite_focus=true

They both have the same failure:

```
  Diagnostics:
    pulumi:pulumi:Stack (azure-eventgrid-p-it-fv-az201-2-eventgrid-fb02cdf7):
      error: Running program '/tmp/p-it-fv-az201-2-eventgrid-fb02cdf7-577505689' failed with an unhandled exception:
      TSError: ⨯ Unable to compile TypeScript:
      index.ts(11,44): error TS2339: Property 'subject' does not exist on type 'ResourceGroupEvent'.
        Property 'subject' does not exist on type 'ResourceActionCancelEventData'.
      index.ts(12,47): error TS2339: Property 'eventType' does not exist on type 'ResourceGroupEvent'.
        Property 'eventType' does not exist on type 'ResourceActionCancelEventData'.
      index.ts(33,44): error TS2339: Property 'subject' does not exist on type 'StorageBlobCreatedEventData'.
      index.ts(49,44): error TS2339: Property 'subject' does not exist on type 'StorageBlobDeletedEventData'.
      
          at createTSError (/tmp/p-it-fv-az201-2-eventgrid-fb02cdf7-577505689/node_modules/ts-node/src/index.ts:261:12)
          at getOutput (/tmp/p-it-fv-az201-2-eventgrid-fb02cdf7-577505689/node_modules/ts-node/src/index.ts:367:40)
          at Object.compile (/tmp/p-it-fv-az201-2-eventgrid-fb02cdf7-577505689/node_modules/ts-node/src/index.ts:558:11)
          at Module.m._compile (/tmp/p-it-fv-az201-2-eventgrid-fb02cdf7-577505689/node_modules/ts-node/src/index.ts:439:43)
          at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
          at Object.require.extensions.<computed> [as .ts] (/tmp/p-it-fv-az201-2-eventgrid-fb02cdf7-577505689/node_modules/ts-node/src/index.ts:442:12)
          at Module.load (internal/modules/cjs/loader.js:950:32)
          at Function.Module._load (internal/modules/cjs/loader.js:790:12)
          at Module.require (internal/modules/cjs/loader.js:974:19)
          at require (internal/modules/cjs/helpers.js:101:18)
```

This is especially confusing because @stack72 and I thought we fixed this in https://github.com/pulumi/pulumi-azure/pull/1030/commits/648e1e2bab4b2871cd444aa23211dc88d03007b7, and the checks passed both [in the PR](https://github.com/pulumi/pulumi-azure/pull/1030) and [when we merged to master](https://github.com/pulumi/pulumi-azure/actions/runs/1796798638). However, the failure above is not something I've been able to replicate locally and it's unclear why this test is failing semi-suddenly.

### PR DESCRIPTION
**Pull request by thomas11**
Resolves #1036

Discovered this while working on something else related to EventGrid. Not sure what the original problem was but this change works for me locally. We'll see about CI shortly.

### CODE REVIEW

**Review by danielrbradley — APPROVED** [review]
Cool - if it works, ship it! :shipit:

File: examples/examples_nodejs_test.go [hunk 1]
```diff
@@ -265,14 +265,29 @@ func TestAccDurableFunctions(t *testing.T) {
...
+			//             "kind": "DELETE"
+			//         },
+			//         "webhookEndpoint.preferredBatchSizeInKilobytes": {
+			//             "kind": "DELETE"
+			//         }
+			//     }
+			// even though the webhook is simply created as
+			//     webhookEndpoint: { url: liveUrl }
+			// in eventgrid/zMixins.ts.
+			ExpectRefreshChanges: true,
```
Comment (flostadler) [inline examples/examples_nodejs_test.go:290]: Do we have a tracking issue for the refresh changes (assuming this is something we want to eventually fix)

**Review by flostadler — APPROVED** [review]
lgtm

File: examples/examples_nodejs_test.go (hunk 1 above)
Comment (thomas11) [reply examples/examples_nodejs_test.go:290]: I don't think this will make the cut to be fixed TBH

File: sdk/nodejs/appservice/zMixins.ts [hunk 2]
```diff
@@ -209,7 +209,7 @@ interface FunctionAppArgsBase {
     /**
      * A `site_config` object as defined below.
      */
-    readonly siteConfig?: pulumi.Input<inputs.appservice.FunctionAppSiteConfig>;
+    readonly siteConfig?: pulumi.Input<inputs.appservice.LinuxFunctionAppSiteConfig>;
```
Comment (mikhailshilkov) [inline sdk/nodejs/appservice/zMixins.ts:212]: That's a bunch of breaking changes, right? Also, isn't Windows supported?

Comment (thomas11) [reply sdk/nodejs/appservice/zMixins.ts:212]: My impression was that it's up to us what kind of Function is created. The `zMixin`'s are our code, and they create the function [internally](https://github.com/pulumi/pulumi-azure/blob/8a052441ca50d039653965ba3d2e7c0121916f46/sdk/nodejs/eventgrid/zMixins.ts#L114-L115).

Regarding breaking changes, yes, it will probably recreate the `EventGridCallbackSubscription`'s. The last commit migrating to LinuxFunctionApp is just an experiment to see whether it fixes the CI build failure. We'll either not include this change, or look at the breaking changes in more detail.

Comment (thomas11) [reply sdk/nodejs/appservice/zMixins.ts]: This PR was merged without the LinuxFunctionApp changes.
